FROM mcr.microsoft.com/vscode/devcontainers/base:ubuntu

# Set up aliases
RUN echo "alias k='kubectl'" >> /home/vscode/.bashrc
RUN echo "alias d='docker'" >> /home/vscode/.bashrc
RUN echo "alias dc='docker compose'" >> /home/vscode/.bashrc
