name: pipeline-frontend

env:
  APP_LOCATION: "/frontend"
  API_LOCATION: ""
  OUTPUT_LOCATION: ""
  BACKEND_API_URL: "http://rg-accelerator-lg1-rick.westeurope.azurecontainer.io:8080/api/"

on:
  push:
    branches: [ main ]

permissions:
  issues: write
  contents: read
  pull-requests: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: ${{ env.APP_LOCATION }}
          api_location: ${{ env.API_LOCATION}}
          output_location: ${{ env.OUTPUT_LOCATION }}
        env:
          BACKEND_API_URL: ${{ env.BACKEND_API_URL }}
