name: pipeline
on:
  push:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '21'
        cache: 'maven'
    - run: ./mvnw package -q
    - uses: azure/docker-login@v2
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: docker build -f src/main/docker/Dockerfile.jvm . -t ${{secrets.REGISTRY_LOGIN_SERVER}}/rick_backend_v1:latest
    - run: docker push ${{secrets.REGISTRY_LOGIN_SERVER}}/rick_backend_v1:latest
    - uses: 'azure/login@v2'
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: 'Deploy to Azure Container Instances'
      uses: 'azure/aci-deploy@v1'
      with:
        resource-group: ${{ secrets.RESOURCE_GROUP }}
        dns-name-label: ${{ secrets.RESOURCE_GROUP }}${{ github.run_number }}-rick
        image: ${{secrets.REGISTRY_LOGIN_SERVER}}/rick_backend_v1:latest
        registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        registry-username: ${{ secrets.REGISTRY_USERNAME }}
        registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        name: rick-backend
        location: 'west europe'
    
    
          
