name: pipeline
on:
  push:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '21'
    - run: ./mvnw package
    - uses: azure/login@v1
      with: 
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
          
