name: pipeline
on:
  push:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '21'
    - run: ./mvnw package -q
    - run: echo ${{ secrets.DOCKER_USR }}
    - run: echo ${{ secrets.DOCKER_TOKEN }}
    - uses: docker/login-action@v3.2.0
      with:
        # Server address of Docker registry. If not set then will default to Docker Hub
        registry: error.acceleratorlg1registry.azurecr.io
        # Username used to log against the Docker registry
        username: ${{ secrets.DOCKER_USR }}
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKER_TOKEN }}
    - run: docker build .
    - uses: azure/login@v1
      with: 
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
          
