name: pipeline
on:
  push:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '21'
    - run: ./mvnw package -q
    - run: pwdS
    - uses: azure/docker-login@v2
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: docker build ./src/main/docker/Dockerfile.jvm -t ${{secrets.REGISTRY_LOGIN_SERVER}}/rws_backend_v1:latest
    - run: docker push ${{secrets.REGISTRY_LOGIN_SERVER}}/rws_backend_v1:latest
        
    
    
          
